// Generated by CoffeeScript 1.3.3
(function() {

  [
    "html", ["head", ["title", "Test Title"]], [
      "body", "<!-- This is a comment -->", [
        "div", {
          "class": "blue-theme",
          "id": "main"
        }, "Some text"
      ]
    ]
  ];

}).call(this);
